#!/usr/bin/env python
"""Install the AutoREC notebook startup guard into the active Python env.

This is useful when a Jupyter kernel dies during training because AutoEIS/Julia
is initialized after TensorFlow/JAX. The guard sets writable runtime locations
and warms up AutoEIS before notebook code runs.
"""

from __future__ import annotations

import site
import sys
from pathlib import Path


GUARD = '''# AutoREC runtime guard.
# Generated by scripts/install_autorec_kernel_guard.py.
# This file is environment-local and does not modify AutoREC source code.
import os as _autorec_os
import sys as _autorec_sys
from pathlib import Path as _autorec_Path

if _autorec_sys.platform == "darwin":
    _autorec_runtime = _autorec_Path.home() / "Library" / "Caches" / "autorec_eis"
else:
    _autorec_runtime = _autorec_Path.home() / ".cache" / "autorec_eis"
(_autorec_runtime / "julia_env").mkdir(parents=True, exist_ok=True)
(_autorec_runtime / "julia_depot").mkdir(parents=True, exist_ok=True)
(_autorec_runtime / "matplotlib").mkdir(parents=True, exist_ok=True)
_autorec_os.environ.setdefault("PYTHON_JULIAPKG_PROJECT", str(_autorec_runtime / "julia_env"))
_autorec_os.environ.setdefault("JULIA_DEPOT_PATH", str(_autorec_runtime / "julia_depot"))
_autorec_os.environ.setdefault("MPLCONFIGDIR", str(_autorec_runtime / "matplotlib"))
_autorec_os.environ.setdefault("PYTHON_JULIACALL_AUTOLOAD_IPYTHON_EXTENSION", "no")
_autorec_os.environ.setdefault("OMP_NUM_THREADS", "1")
_autorec_os.environ.setdefault("MKL_NUM_THREADS", "1")
_autorec_os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
_autorec_os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")

if (
    any(_arg == "-f" or _arg.startswith("--f=") for _arg in _autorec_sys.argv)
    or any("kernel-" in _arg and _arg.endswith(".json") for _arg in _autorec_sys.argv)
):
    try:
        import autoeis as _autorec_autoeis
        _autorec_autoeis.core.ec.karva_to_tree("+RR")
        print("[AutoREC startup] AutoEIS/Juliacall initialized before notebook code", flush=True)
    except Exception as _autorec_exc:
        print(f"[AutoREC startup] AutoEIS/Juliacall warmup failed: {_autorec_exc!r}", flush=True)
'''


def get_sitecustomize_path() -> Path:
    site_packages = site.getsitepackages()
    if not site_packages:
        raise RuntimeError("Could not locate site-packages for the active Python environment.")
    return Path(site_packages[0]) / "sitecustomize.py"


def main() -> int:
    path = get_sitecustomize_path()
    if path.exists():
        existing = path.read_text()
        if "AutoREC runtime guard" not in existing:
            backup = path.with_suffix(".py.autorec-backup")
            backup.write_text(existing)
            print(f"Existing sitecustomize.py backed up to: {backup}")

    path.write_text(GUARD)
    print(f"Installed AutoREC kernel guard to: {path}")
    print(f"Python executable: {sys.executable}")
    print("Restart the Jupyter kernel after running this script.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
